name: Update Release Notes

on:
  push:
    tags:
      - '*'
permissions:
  contents: write
jobs:
  update-release-notes:
    runs-on: ubuntu-latest
    env:
      TAG_NAME: ${{ github.ref_name }}
      BRANCH_NAME: update-release-notes-${{ github.ref_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Run update_releases.py script
        run: python ./docs/update_releases.py

      - name: Check for changes
        id: git-check
        run: |
          git diff --quiet || echo "::set-output name=changes_detected::true"

      - run: git diff
      - name: Create new branch and commit changes if there are any
        if: steps.git-check.outputs.changes_detected
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update release notes for ${{ env.TAG_NAME }}"
          branch: ${{ env.BRANCH_NAME }}
          file_pattern: docs/docs/en/release.md
          commit_user_name: 'github-actions'
          commit_user_email: 'github-actions@github.com'

      - name: Create Pull Request
        if: steps.git-check.outputs.changes_detected
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.BRANCH_NAME }}
          title: "Update Release Notes for ${{ env.TAG_NAME }}"
          commit-message: "Update Release Notes for ${{ env.TAG_NAME }}"
          body: "This is an automated pull request to update the release notes for ${{ env.TAG_NAME }}"
          base: "main" # The branch you want to merge into
